services:
  - type: web
    name: digi-vue
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
